BTClient Class Reference
BTClient Class Reference
The BTClient defines the behaviour of a BitTorrent client.
#include <BTClient.h>
Classes
struct PacketQueueElement
Struct that identifies a queueing packet.
Public Member Functions
BTClient ()
void handlePeerIsGone (const char *peer)
Does the nessecary things when a peer leaves the swarm.
void freeGate (const char *peer)
Disconnects the gate through which peer is reachable.
void setSeeder ()
Sets the seeder status.
void setLeecher (simtime_t aTime, simtime_t sTime)
Sets the leecher state.
void initialize ()
Initialises the BTClient class, this is called by the OMNeT++ simulation core.
void handleMessage (cMessage *msg)
Handles incomming messages, this is called by the OMNeT++ simulation core.
void finish ()
Collects the nessecary statistics, this is called by the OMNeT++ simulation core at the end of the simulation.
Private Member Functions
void handleTrackerResponse (TrackerResponse *trq)
Handles incomming tracker responses.
void handleHandshake (Handshake *hds)
Handles incomming handshakes.
void handleBitfield (BitField *hds)
Handles incomming bitfields.
void handleHavePiece (HavePiece *hpc)
Handles incomming have-piece messages.
void handleKeepAliveTimer (cPacket *timer)
Handles timer events.
void handleInterested (Interested *inr)
Handles incomming interested messages.
void handleNotInterested (NotInterested *inr)
Handles incomming not-interested messages.
void handleSelfMessage (cPacket *msg)
Handles self messages.
void handleUnChoke (UnChoke *msg)
Handles incomming unChoke messages.
void handlePieceRequest (PieceRequest *prq)
Handles incomming piece requests.
void handlePiece (Piece *pce)
Handles incomming pieces.
void handleChoke (Choke *uch)
Handles incomming choke messages.
void handleCancel (Cancel *cnl)
Handles incomming cancel messages.
int makeConnectionToPeer (const char *peer)
Establishes a connection with peer.
void deleteAllConnections ()
Deletes all the connections to other identities in the swarm.
void requestNewPiece (const char *peer_id)
Generates a new piece request and sends it to peer.
void chokePeer (const char *client, bool choke)
Chokes a peer and stores the information accordingly.
void sendToTracker (cPacket *msg)
Sends a message to the traker.
void freeBothGates (const char *peer)
Disconnects the gates (link) to another peer.
int queuePacket (const char *client, cPacket *msg, simtime_t delay)
Enqueues a packet waiting to be send.
void sendMessage ()
Transmits the first message in the packetQueue.
int do_sendToClient (const char *client, cPacket *msg, simtime_t delay)
Sends a message to a peer.
Private Attributes
PieceManager * pieceManager
Pointer to the class that manages the pieces.
PeerManager * peerManager
Pointer to the class that manages data related to connected peers.
cPacket * transmissionPacket
Pointer to a message used for indication transmission inprogress.
cPacket * timer
Pointer to a message used for general purpose timers.
vector< PacketQueueElement > packetQueue
Queue for outgoing messages.
cOutVector incomingRequests
Output vector (see OMNeT) that tracks incoming piece requests.
cOutVector outgoingRequests
Output vector (see OMNeT) that tracks outgoing piece requests.
cOutVector connectedPeers
Output vector (see OMNeT) that tracks the amount of connected peers.
cOutVector disconnectedPeers
Output vector (see OMNeT) that tracks disconnection of peers.
cOutVector haveMessages
Output vector (see OMNeT) that tracks have message traffic.
simtime_t seed_time
The amount of time that will be seeded once the seeder states is attained.
simtime_t start_time
The time when the peer will join the swarm.
simtime_t stop_time
The time when the peer will leave the swarm.
double session_size_in
TO FILL OUT!!!!!!!!!!!!!!!!!!! Incoming session size statistic ??????
double session_size_out
TO FILL OUT!!!!!!!!!!!!!!!!!!! Outgoing session size statistic ??????
string tracker
Stores the URL of the tracker.
bool busySending
Denotes if module is busy with sending data.
bool leecher
Set if peer is leecher.
bool seeder
Set if peer is seeder.
bool endGameMode
Defines if peer is in end game mode.
bool gatesOpen
Sets all conenctions open for traffic.
bool initialSeeder
Defines if the peer is a seeder from the moment it joined the swarm.
int assymetricLinks
Defines if there are assymetrical links between the peers in the P2P network.
int trackerGate
Defines the gate through which the BTTracker is reachable.
simtime_t arrivalTime
Defines the arrival time.
simtime_t seedingTime
Defines the seeding time.
int myID
Stores the ID of the client.
int algorithm
Defines the algorithm used for piece selection.
unsigned int chokeRound
Counts the amount of times the choke timer has been triggered.
unsigned int downloaded
Tracks the amount of bytes that has been downloaded.
unsigned int uploaded
Tracks the amount of bytes that has been uploaded.
vector< string > endGameModePeers
Stores the peers that are participating in the end-game mode.
vector< Piece * > pendingMessages
Stores the messages that are waiting to be send.
ClientAssigner * ca
Pointer to the ClientAssigner module in the simulator.
Detailed Description
The BTClient defines the behaviour of a BitTorrent client.
Date:
2009-06-07
Version:
1.2
Author:
Blekinge Institute of Technology TEK-ATS
Constructor & Destructor Documentation
BTClient::BTClient ()
References algorithm, arrivalTime, assymetricLinks, busySending, chokeRound, downloaded, endGameMode, gatesOpen, initialSeeder, leecher, peerManager, pieceManager, seeder, seedingTime, session_size_in, session_size_out, timer, trackerGate, Transmission_Ready, transmissionPacket, and uploaded.
Member Function Documentation
void BTClient::chokePeer (const char * client, bool choke) [private]
Chokes a peer and stores the information accordingly.
Parameters:
client Peer to be choked
choke Choke or unChoke the peer
References Choke_Peer, MessageHeader_Length, BitTorrent::peer_id, peerManager, queuePacket(), PeerManager::setChokePeer(), and UnChoke_Peer.
Referenced by handleKeepAliveTimer().
void BTClient::deleteAllConnections () [private]
Deletes all the connections to other identities in the swarm.
References BitTorrent::freeGate(), and BitTorrent::peer_id.
Referenced by handleSelfMessage().
int BTClient::do_sendToClient (const char * client, cPacket * msg, simtime_t delay) [private]
Sends a message to a peer.
Is called through queuePacket, don't use this call directly!
Parameters:
msg Pointer to the message to be send
client The ID of the peer to which message will be send
delay The waiting time before the message will be send
References busySending, PeerManager::getGate(), BitTorrent::getPeerID(), peerManager, session_size_out, PeerManager::setGate(), stringify(), and transmissionPacket.
Referenced by sendMessage().
void BTClient::finish ()
Collects the nessecary statistics, this is called by the OMNeT++ simulation core at the end of the simulation.
References arrivalTime, initialSeeder, seed_time, session_size_in, session_size_out, stop_time, and transmissionPacket.
void BTClient::freeBothGates (const char * peer) [private]
Disconnects the gates (link) to another peer.
This operation also disconnects the gates (see OMNeT) at the other side of the connection.
References BitTorrent::freeGate(), PeerManager::getGate(), BitTorrent::peer_id, peerManager, and PeerManager::setGate().
void BTClient::freeGate (const char * peer) [virtual]
Disconnects the gate through which peer is reachable.
Implements BitTorrent.
References PeerManager::getGate(), peerManager, and PeerManager::setGate().
void BTClient::handleBitfield (BitField * hds) [private]
Handles incomming bitfields.
References PieceManager::addPieceArrayOfPeer(), BITField, PieceManager::buildPieceIndex(), PeerManager::conOpenend(), PieceManager::getLengthOfPieceArray(), PieceManager::getPieceArrayCompleteOfPeer(), PieceManager::getPieceArrayEmpty(), PeerManager::getStatus(), Interested_Peer, leecher, MessageHeader_Length, BitTorrent::peer_id, peerManager, pieceManager, queuePacket(), PieceManager::setInterestedInPeer(), PeerManager::setPeerAsSeeder(), and PieceManager::writePiecesToMessage().
Referenced by handleMessage().
void BTClient::handleCancel (Cancel * cnl) [private]
Handles incomming cancel messages.
References pendingMessages.
Referenced by handleMessage().
void BTClient::handleChoke (Choke * uch) [private]
Handles incomming choke messages.
References BitTorrent::peer_id, pieceManager, and PieceManager::setChokedByPeer().
Referenced by handleMessage().
void BTClient::handleHandshake (Handshake * hds) [private]
Handles incomming handshakes.
References PeerManager::addPeer(), BITField, connectedPeers, PeerManager::conOpenend(), PeerManager::conPending(), PeerManager::getAmountOfConnections(), PieceManager::getLengthOfPieceArray(), PeerManager::getStatus(), HandShake, HandShake_Length, MessageHeader_Length, BitTorrent::peer_id, peerManager, pieceManager, queuePacket(), PeerManager::registredPeer(), and PieceManager::writePiecesToMessage().
Referenced by handleMessage().
void BTClient::handleHavePiece (HavePiece * hpc) [private]
Handles incomming have-piece messages.
References PieceManager::addPiece(), PieceManager::getInterestedInPeer(), PieceManager::getPieceArrayCompleteOfPeer(), haveMessages, Interested_Peer, PieceManager::isThereSomethingToBeInterestedIn(), leecher, MessageHeader_Length, BitTorrent::peer_id, peerManager, pieceManager, queuePacket(), PieceManager::setInterestedInPeer(), and PeerManager::setPeerAsSeeder().
Referenced by handleMessage().
void BTClient::handleInterested (Interested * inr) [private]
Handles incomming interested messages.
References peerManager, and PeerManager::setPeerInterested().
Referenced by handleMessage().
void BTClient::handleKeepAliveTimer (cPacket * timer) [private]
Handles timer events.
References chokePeer(), chokeRound, PeerManager::conPending(), downloaded, BitTorrent::getAmountOfEmptyGates(), PeerManager::getChoked(), PeerManager::getFastestDownloader(), PeerManager::getIntrests(), PeerManager::getNewPeers(), PeerManager::getPeerChoked(), PeerManager::getRandomChoked(), PeerManager::getRandomInterested(), PeerManager::getRecentlyUnchoked(), PieceManager::getRemainingDownload(), HandShake, HandShake_Length, PeerManager::isPeerChoked(), leecher, makeConnectionToPeer(), BitTorrent::peer_id, peerManager, pieceManager, queuePacket(), PeerManager::resetDownload(), PeerManager::resetPendingPeers(), seeder, sendToTracker(), PeerManager::setChokePeer(), Tracker_Request, and uploaded.
Referenced by handleSelfMessage().
void BTClient::handleMessage (cMessage * msg)
Handles incomming messages, this is called by the OMNeT++ simulation core.
References BITField, Cancel_Piece, Choke_Peer, Default, handleBitfield(), handleCancel(), handleChoke(), handleHandshake(), handleHavePiece(), handleInterested(), handleNotInterested(), handlePiece(), handlePieceRequest(), handleSelfMessage(), handleTrackerResponse(), handleUnChoke(), HandShake, Have_Piece, Interested_Peer, KeepAlive_Peer, leecher, New_Piece, Piece_Request, session_size_in, Tracker_Response, UnChoke_Peer, and UnInterested_Peer.
void BTClient::handleNotInterested (NotInterested * inr) [private]
Handles incomming not-interested messages.
References Choke_Peer, PeerManager::getPeerChoked(), MessageHeader_Length, BitTorrent::peer_id, peerManager, queuePacket(), PeerManager::setChokePeer(), and PeerManager::setPeerInterested().
Referenced by handleMessage().
void BTClient::handlePeerIsGone (const char * peer)
Does the nessecary things when a peer leaves the swarm.
Parameters:
peer The Peer ID of the peer that leaves the swarm
References PeerManager::deletePeer(), disconnectedPeers, PieceManager::freePeer(), PeerManager::getAmountOfConnections(), PeerManager::getStatus(), OPEN, peerManager, PENDING, pieceManager, and PeerManager::registredPeer().
Referenced by ClientAssigner::peerIsLeaving().
void BTClient::handlePiece (Piece * pce) [private]
Handles incomming pieces.
References ca, Cancel_Piece, PieceManager::deleteIncompletePieces(), downloaded, endGameMode, endGameModePeers, PieceManager::getAmountOfCompletePieces(), PieceManager::getAmountOfPieces(), PieceManager::getAmountOfPiecesInProgress(), PieceManager::getBlockPresentOfIncompletePeer(), PieceManager::getChokedByPeer(), PieceManager::getDownloadListOfPeers(), PieceManager::getInterestedInPeer(), PieceManager::getLastBlocks(), PeerManager::getPeerList(), PieceManager::getPieceArrayComplete(), PieceManager::getRemainingDownload(), PeerManager::getStatus(), Have_Length, Have_Piece, PeerManager::isPeerASeeder(), PieceManager::isThereSomethingToBeInterestedIn(), Leaving_Swarm, leecher, MessageHeader_Length, myID, BitTorrent::peer_id, ClientAssigner::peerIsSeeder(), peerManager, Piece_Request, pieceManager, queuePacket(), PeerManager::registerDownload(), Request_Lenght, requestNewPiece(), seed_time, seeder, seedingTime, sendToTracker(), PieceManager::setBlock(), PieceManager::setSeeder(), stop_time, Tracker_Request, UnInterested_Peer, and uploaded.
Referenced by handleMessage().
void BTClient::handlePieceRequest (PieceRequest * prq) [private]
Handles incomming piece requests.
References PieceManager::getAmountOfPieces(), PieceManager::getPiecePresent(), incomingRequests, New_Piece, BitTorrent::peer_id, pendingMessages, PieceHeader_Length, and pieceManager.
Referenced by handleMessage().
void BTClient::handleSelfMessage (cPacket * msg) [private]
Handles self messages.
References busySending, ca, deleteAllConnections(), downloaded, gatesOpen, PieceManager::getRemainingDownload(), handleKeepAliveTimer(), KeepAlive_Timer, Leaving_Swarm, myID, New_Piece, packetQueue, BitTorrent::peer_id, ClientAssigner::peerIsLeaving(), peerManager, pendingMessages, pieceManager, queuePacket(), PeerManager::registerDownload(), sendMessage(), sendToTracker(), stringify(), timer, Tracker_Request, Transmission_Ready, and uploaded.
Referenced by handleMessage().
void BTClient::handleTrackerResponse (TrackerResponse * trq) [private]
Handles incomming tracker responses.
References PeerManager::addPeer(), PeerManager::conPending(), PeerManager::getAmountOfConnections(), BitTorrent::getAmountOfEmptyGates(), PeerManager::getNewPeers(), HandShake, makeConnectionToPeer(), BitTorrent::peer_id, peerManager, and queuePacket().
Referenced by handleMessage().
void BTClient::handleUnChoke (UnChoke * msg) [private]
Handles incomming unChoke messages.
References pieceManager, requestNewPiece(), and PieceManager::setChokedByPeer().
Referenced by handleMessage().
void BTClient::initialize ()
Initialises the BTClient class, this is called by the OMNeT++ simulation core.
References algorithm, arrivalTime, assymetricLinks, busySending, ca, connectedPeers, disconnectedPeers, downloaded, endGameMode, BitTorrent::getFreeGate(), PieceManager::getRemainingDownload(), TorrentFile::getValue(), haveMessages, incomingRequests, PieceManager::init(), PieceManager::initialisePieceArray(), leecher, myID, outgoingRequests, BitTorrent::peer_id, peerManager, pieceManager, seeder, PieceManager::setBlockLength(), PeerManager::setPeerID(), PieceManager::setPeerID(), PieceManager::setSeeder(), stringify(), BitTorrent::torrentFile, tracker, Tracker_Request, trackerGate, uploaded, and BitTorrent::URL.
int BTClient::makeConnectionToPeer (const char * peer) [private]
Establishes a connection with peer.
Returns:
Whether the connection could be established
Return values:
0 succesfull
-1 not succesfull
References assymetricLinks, BitTorrent::getFreeGate(), peerManager, PeerManager::setGate(), and stringify().
Referenced by handleKeepAliveTimer(), and handleTrackerResponse().
int BTClient::queuePacket (const char * client, cPacket * msg, simtime_t delay) [private]
Enqueues a packet waiting to be send.
Parameters:
msg Pointer to the message to be send
client The ID of the peer to which message will be send
delay The waiting time before the message will be send
References busySending, BTClient::PacketQueueElement::client, BTClient::PacketQueueElement::delay, BTClient::PacketQueueElement::packet, packetQueue, and sendMessage().
Referenced by chokePeer(), handleBitfield(), handleHandshake(), handleHavePiece(), handleKeepAliveTimer(), handleNotInterested(), handlePiece(), handleSelfMessage(), handleTrackerResponse(), and requestNewPiece().
void BTClient::requestNewPiece (const char * peer_id) [private]
Generates a new piece request and sends it to peer.
If no piece could be found to download then a not interested message will be send instead.
References endGameMode, blockID::index, blockID::length, MessageHeader_Length, blockID::offset, outgoingRequests, BitTorrent::peer_id, Piece_Request, pieceManager, PieceManager::pieceRequest(), queuePacket(), Request_Lenght, and UnInterested_Peer.
Referenced by handlePiece(), and handleUnChoke().
void BTClient::sendMessage () [private]
Transmits the first message in the packetQueue.
References do_sendToClient(), and packetQueue.
Referenced by handleSelfMessage(), and queuePacket().
void BTClient::sendToTracker (cPacket * msg) [private]
Sends a message to the traker.
References session_size_out, and trackerGate.
Referenced by handleKeepAliveTimer(), handlePiece(), and handleSelfMessage().
void BTClient::setLeecher (simtime_t aTime, simtime_t sTime)
Sets the leecher state.
Parameters:
aTime The arrival time in the swarm
sTime The time the leecher will be seeding once it is turned into a seeder
References arrivalTime, leecher, and seedingTime.
Referenced by ClientAssigner::initialize().
void BTClient::setSeeder ()
Sets the seeder status.
When this function is called the peer will behave as a seeder.
References initialSeeder, seed_time, and seeder.
Referenced by ClientAssigner::initialize().
Member Data Documentation
int BTClient::algorithm [private]
Defines the algorithm used for piece selection.
This value is laoded from the initialisation file at the startup of the simulation (see OMNeT).
Referenced by BTClient(), and initialize().
simtime_t BTClient::arrivalTime [private]
Defines the arrival time.
This value is set by the ClientAssigner upon creation of the peer. This for statistical purposes.
Referenced by BTClient(), finish(), initialize(), and setLeecher().
int BTClient::assymetricLinks [private]
Defines if there are assymetrical links between the peers in the P2P network.
Referenced by BTClient(), initialize(), and makeConnectionToPeer().
bool BTClient::busySending [private]
Denotes if module is busy with sending data.
Referenced by BTClient(), do_sendToClient(), handleSelfMessage(), initialize(), and queuePacket().
ClientAssigner* BTClient::ca [private]
Pointer to the ClientAssigner module in the simulator.
Referenced by handlePiece(), handleSelfMessage(), and initialize().
unsigned int BTClient::chokeRound [private]
Counts the amount of times the choke timer has been triggered.
Referenced by BTClient(), and handleKeepAliveTimer().
cOutVector BTClient::connectedPeers [private]
Output vector (see OMNeT) that tracks the amount of connected peers.
Referenced by handleHandshake(), and initialize().
cOutVector BTClient::disconnectedPeers [private]
Output vector (see OMNeT) that tracks disconnection of peers.
Referenced by handlePeerIsGone(), and initialize().
unsigned int BTClient::downloaded [private]
Tracks the amount of bytes that has been downloaded.
Referenced by BTClient(), handleKeepAliveTimer(), handlePiece(), handleSelfMessage(), and initialize().
bool BTClient::endGameMode [private]
Defines if peer is in end game mode.
Referenced by BTClient(), handlePiece(), initialize(), and requestNewPiece().
vector<string> BTClient::endGameModePeers [private]
Stores the peers that are participating in the end-game mode.
Referenced by handlePiece().
bool BTClient::gatesOpen [private]
Sets all conenctions open for traffic.
Deprecated:
This variable is currently not used and will be deleted in future releases.
Referenced by BTClient(), and handleSelfMessage().
cOutVector BTClient::haveMessages [private]
Output vector (see OMNeT) that tracks have message traffic.
Referenced by handleHavePiece(), and initialize().
cOutVector BTClient::incomingRequests [private]
Output vector (see OMNeT) that tracks incoming piece requests.
Referenced by handlePieceRequest(), and initialize().
bool BTClient::initialSeeder [private]
Defines if the peer is a seeder from the moment it joined the swarm.
Referenced by BTClient(), finish(), and setSeeder().
bool BTClient::leecher [private]
Set if peer is leecher.
Referenced by BTClient(), handleBitfield(), handleHavePiece(), handleKeepAliveTimer(), handleMessage(), handlePiece(), initialize(), and setLeecher().
int BTClient::myID [private]
Stores the ID of the client.
Referenced by handlePiece(), handleSelfMessage(), and initialize().
cOutVector BTClient::outgoingRequests [private]
Output vector (see OMNeT) that tracks outgoing piece requests.
Referenced by initialize(), and requestNewPiece().
vector<PacketQueueElement> BTClient::packetQueue [private]
Queue for outgoing messages.
Referenced by handleSelfMessage(), queuePacket(), and sendMessage().
PeerManager* BTClient::peerManager [private]
Pointer to the class that manages data related to connected peers.
Referenced by BTClient(), chokePeer(), do_sendToClient(), freeBothGates(), freeGate(), handleBitfield(), handleHandshake(), handleHavePiece(), handleInterested(), handleKeepAliveTimer(), handleNotInterested(), handlePeerIsGone(), handlePiece(), handleSelfMessage(), handleTrackerResponse(), initialize(), and makeConnectionToPeer().
vector<Piece*> BTClient::pendingMessages [private]
Stores the messages that are waiting to be send.
Messages are placed in a queue because measurements have shown that piece messages are processed according to a specific distribution. Queuing these message gives the abillity to control this behaviour. This is necassery because OMNeT is an event based simulator.
Referenced by handleCancel(), handlePieceRequest(), and handleSelfMessage().
PieceManager* BTClient::pieceManager [private]
Pointer to the class that manages the pieces.
Referenced by BTClient(), handleBitfield(), handleChoke(), handleHandshake(), handleHavePiece(), handleKeepAliveTimer(), handlePeerIsGone(), handlePiece(), handlePieceRequest(), handleSelfMessage(), handleUnChoke(), initialize(), and requestNewPiece().
simtime_t BTClient::seed_time [private]
The amount of time that will be seeded once the seeder states is attained.
This value is set by the ClientAssigner upon creation of the peer. This for statistical purposes.
Referenced by finish(), handlePiece(), and setSeeder().
bool BTClient::seeder [private]
Set if peer is seeder.
Referenced by BTClient(), handleKeepAliveTimer(), handlePiece(), initialize(), and setSeeder().
simtime_t BTClient::seedingTime [private]
Defines the seeding time.
This value is set by the ClientAssigner upon creation of the peer. This for statistical purposes.
Referenced by BTClient(), handlePiece(), and setLeecher().
double BTClient::session_size_in [private]
TO FILL OUT!!!!!!!!!!!!!!!!!!! Incoming session size statistic ??????
Referenced by BTClient(), finish(), and handleMessage().
double BTClient::session_size_out [private]
TO FILL OUT!!!!!!!!!!!!!!!!!!! Outgoing session size statistic ??????
Referenced by BTClient(), do_sendToClient(), finish(), and sendToTracker().
simtime_t BTClient::start_time [private]
The time when the peer will join the swarm.
Deprecated:
This variable is currently not used and will be deleted in future releases.
simtime_t BTClient::stop_time [private]
The time when the peer will leave the swarm.
Deprecated:
This variable is currently not used and will be deleted in future releases.
Referenced by finish(), and handlePiece().
cPacket* BTClient::timer [private]
Pointer to a message used for general purpose timers.
Referenced by BTClient(), and handleSelfMessage().
string BTClient::tracker [private]
Stores the URL of the tracker.
Referenced by initialize().
int BTClient::trackerGate [private]
Defines the gate through which the BTTracker is reachable.
Referenced by BTClient(), initialize(), and sendToTracker().
cPacket* BTClient::transmissionPacket [private]
Pointer to a message used for indication transmission inprogress.
Referenced by BTClient(), do_sendToClient(), and finish().
unsigned int BTClient::uploaded [private]
Tracks the amount of bytes that has been uploaded.
Referenced by BTClient(), handleKeepAliveTimer(), handlePiece(), handleSelfMessage(), and initialize().
The documentation for this class was generated from the following files:
BTClient.h
BTClient.cc