PeerManager Class Reference
PeerManager Class Reference
The PeerManager class manages client infornation for a BT client.
#include <PeerManager.h>
Public Member Functions
int getStatus (const char *peer)
Returns whether peer_id is choked by this client.
void conOpenend (const char *peer, simtime_t time)
Sets the conenction to peer to established.
void conPending (const char *peer, simtime_t time)
Sets the conenction to peer to pending.
void addPeer (const char *peer)
Adds an empty entry for peer in the database.
int registredPeer (const char *peer)
Returns if peer has an entry in the database.
int getPeerChoked (const char *peer)
Returns whether peer is choked by this client.
void setPeerAsSeeder (const char *peer)
Sets the status of peer to seeder in the database.
int isPeerASeeder (const char *peer)
Returns the seeder/leecher status of peer.
int getAmountOfConnections ()
Returns the amount of established conenctions.
void getNewPeers (vector< string > *peer)
Pushes back all peers that are not connected in the peer vector.
void getPeerList (vector< string > *peerList)
Pushes back all peers that can be found in the database in the peerList vector.
void deletePeer (const char *peer)
Deletes the entry in the database correspending to peer.
int resetPendingPeers (simtime_t time)
Sets all the PENDING connections to CLOSED that are pending for more then 1 minute.
int getGate (const char *peer)
Returns the gate to which peer is conencted to.
void setGate (const char *peer, int gate)
Sets the gate to which peer is conencted to.
void resetDownload ()
Sets the download tracks off every peer entry to 0.
void registerDownload (const char *peer, int byte)
Adds the download to the peers information space.
void getFastestDownloader (vector< string > *peerList)
Pushes back the three fastest downloaders in the peerList vector.
void getRecentlyUnchoked (vector< string > *peerList)
Pushes back the three most recently unchoked peers in the peerList vector.
void setChokePeer (const char *peer, bool choke, simtime_t time)
Sets the choke state of peer and records the timestamp.
void isPeerChoked (vector< string > *unChoked, vector< string > *choked)
Pushes back all the peers in the choked vector that are choked and not in the unChoked vector.
const char * getRandomInterested ()
Returns a random interested and choked peer.
const char * getRandomChoked ()
Returns a random choked and interested peer.
void setPeerInterested (const char *peer, bool interest)
Sets the interested parameter of peer.
int getIntrests ()
Returns if there are interested peers or not.
int getChoked ()
Returns if there are choked peers or not.
void setPeerID (string name)
Registers the ID of the peer that owns this class.
void writePeers ()
Writes the content of the peer database to cout.
~PeerManager ()
Destroys this PeerManager.
Private Member Functions
vector< Peer >::iterator peerLookUp (const char *peer)
Looks up the pointer to a Peer struct containing information of peer.
Private Attributes
string peer_id
Defines the Peer ID of the peer that owns this class.
vector< Peer > peers
Array of peer information of which peer_id has notice of.
Detailed Description
The PeerManager class manages client infornation for a BT client.
Date:
2009-03-06
Version:
1.2
Author:
Blekinge Institute of Technology TEK-ATS
Constructor & Destructor Documentation
PeerManager::~PeerManager ()
Destroys this PeerManager.
References writePeers().
Member Function Documentation
void PeerManager::addPeer (const char * peer)
Adds an empty entry for peer in the database.
References Peer::choked, CLOSED, Peer::downloaded, Peer::gate, Peer::interested, Peer::peer_id, peerLookUp(), peers, Peer::seeder, Peer::status, Peer::statusChange, and Peer::time.
Referenced by BTClient::handleHandshake(), and BTClient::handleTrackerResponse().
void PeerManager::conOpenend (const char * peer, simtime_t time)
Sets the conenction to peer to established.
References OPEN, peerLookUp(), and peers.
Referenced by BTClient::handleBitfield(), and BTClient::handleHandshake().
void PeerManager::conPending (const char * peer, simtime_t time)
Sets the conenction to peer to pending.
References peerLookUp(), peers, and PENDING.
Referenced by BTClient::handleHandshake(), BTClient::handleKeepAliveTimer(), and BTClient::handleTrackerResponse().
void PeerManager::deletePeer (const char * peer)
Deletes the entry in the database correspending to peer.
References peerLookUp(), and peers.
Referenced by BTClient::handlePeerIsGone().
int PeerManager::getAmountOfConnections ()
Returns the amount of established conenctions.
References peers.
Referenced by BTClient::handleHandshake(), BTClient::handlePeerIsGone(), and BTClient::handleTrackerResponse().
int PeerManager::getChoked ()
Returns if there are choked peers or not.
Return values:
0 There are choked peers
-1 There are no choked peers
References peers.
Referenced by getRandomChoked(), and BTClient::handleKeepAliveTimer().
void PeerManager::getFastestDownloader (vector< string > * peerList)
Pushes back the three fastest downloaders in the peerList vector.
References peers.
Referenced by BTClient::handleKeepAliveTimer().
int PeerManager::getGate (const char * peer)
Returns the gate to which peer is conencted to.
References peerLookUp(), and peers.
Referenced by BTClient::do_sendToClient(), BTClient::freeBothGates(), and BTClient::freeGate().
int PeerManager::getIntrests ()
Returns if there are interested peers or not.
Return values:
0 There are interested peers
-1 There are no interested peers
References peers.
Referenced by getRandomInterested(), and BTClient::handleKeepAliveTimer().
void PeerManager::getNewPeers (vector< string > * peer)
Pushes back all peers that are not connected in the peer vector.
References CLOSED, and peers.
Referenced by BTClient::handleKeepAliveTimer(), and BTClient::handleTrackerResponse().
int PeerManager::getPeerChoked (const char * peer)
Returns whether peer is choked by this client.
Return values:
0 peer is unchoked.
-1 peer is choked
References peerLookUp().
Referenced by BTClient::handleKeepAliveTimer(), and BTClient::handleNotInterested().
void PeerManager::getPeerList (vector< string > * peerList)
Pushes back all peers that can be found in the database in the peerList vector.
References peers.
Referenced by BTClient::handlePiece().
const char * PeerManager::getRandomChoked ()
Returns a random choked and interested peer.
References getChoked(), and peers.
Referenced by BTClient::handleKeepAliveTimer().
const char * PeerManager::getRandomInterested ()
Returns a random interested and choked peer.
References getIntrests(), and peers.
Referenced by BTClient::handleKeepAliveTimer().
void PeerManager::getRecentlyUnchoked (vector< string > * peerList)
Pushes back the three most recently unchoked peers in the peerList vector.
References peers.
Referenced by BTClient::handleKeepAliveTimer().
int PeerManager::getStatus (const char * peer)
Returns whether peer_id is choked by this client.
References peerLookUp(), and peers.
Referenced by BTClient::handleBitfield(), BTClient::handleHandshake(), BTClient::handlePeerIsGone(), and BTClient::handlePiece().
int PeerManager::isPeerASeeder (const char * peer)
Returns the seeder/leecher status of peer.
Return values:
true peer is a seeder
false peer is a leecher
-1 peer is not found in the database
References peerLookUp().
Referenced by BTClient::handlePiece().
void PeerManager::isPeerChoked (vector< string > * unChoked, vector< string > * choked)
Pushes back all the peers in the choked vector that are choked and not in the unChoked vector.
References peers.
Referenced by BTClient::handleKeepAliveTimer().
vector< Peer >::iterator PeerManager::peerLookUp (const char * peer) [private]
Looks up the pointer to a Peer struct containing information of peer.
References peers.
Referenced by addPeer(), conOpenend(), conPending(), deletePeer(), getGate(), getPeerChoked(), getStatus(), isPeerASeeder(), registerDownload(), registredPeer(), setChokePeer(), setGate(), setPeerAsSeeder(), and setPeerInterested().
void PeerManager::registerDownload (const char * peer, int byte)
Adds the download to the peers information space.
References peerLookUp(), and peers.
Referenced by BTClient::handlePiece(), and BTClient::handleSelfMessage().
int PeerManager::registredPeer (const char * peer)
Returns if peer has an entry in the database.
Return values:
0 peer is present.
-1 peer is not present
References peerLookUp(), and peers.
Referenced by BTClient::handleHandshake(), and BTClient::handlePeerIsGone().
void PeerManager::resetDownload ()
Sets the download tracks off every peer entry to 0.
References peers.
Referenced by BTClient::handleKeepAliveTimer().
int PeerManager::resetPendingPeers (simtime_t time)
Sets all the PENDING connections to CLOSED that are pending for more then 1 minute.
References CLOSED, peers, and PENDING.
Referenced by BTClient::handleKeepAliveTimer().
void PeerManager::setChokePeer (const char * peer, bool choke, simtime_t time)
Sets the choke state of peer and records the timestamp.
References peerLookUp().
Referenced by BTClient::chokePeer(), BTClient::handleKeepAliveTimer(), and BTClient::handleNotInterested().
void PeerManager::setGate (const char * peer, int gate)
Sets the gate to which peer is conencted to.
References peerLookUp(), and peers.
Referenced by BTClient::do_sendToClient(), BTClient::freeBothGates(), BTClient::freeGate(), and BTClient::makeConnectionToPeer().
void PeerManager::setPeerAsSeeder (const char * peer)
Sets the status of peer to seeder in the database.
References peerLookUp().
Referenced by BTClient::handleBitfield(), and BTClient::handleHavePiece().
void PeerManager::setPeerID (string name)
Registers the ID of the peer that owns this class.
This is only used in case debug messages want to be printed.
References peer_id.
Referenced by BTClient::initialize().
void PeerManager::setPeerInterested (const char * peer, bool interest)
Sets the interested parameter of peer.
Parameters:
interest the state to which peer will be set
References peerLookUp().
Referenced by BTClient::handleInterested(), and BTClient::handleNotInterested().
void PeerManager::writePeers ()
Writes the content of the peer database to cout.
References peers.
Referenced by ~PeerManager().
Member Data Documentation
string PeerManager::peer_id [private]
Defines the Peer ID of the peer that owns this class.
Referenced by setPeerID().
vector<Peer> PeerManager::peers [private]
Array of peer information of which peer_id has notice of.
Referenced by addPeer(), conOpenend(), conPending(), deletePeer(), getAmountOfConnections(), getChoked(), getFastestDownloader(), getGate(), getIntrests(), getNewPeers(), getPeerList(), getRandomChoked(), getRandomInterested(), getRecentlyUnchoked(), getStatus(), isPeerChoked(), peerLookUp(), registerDownload(), registredPeer(), resetDownload(), resetPendingPeers(), setGate(), and writePeers().
The documentation for this class was generated from the following files:
PeerManager.h
PeerManager.cc