BTTracker Class Reference
BTTracker Class Reference
The BTTracker class implements the tracker functionalities.
#include <BTTracker.h>
Public Member Functions
BTTracker ()
void freeGate (const char *peer)
Frees the gate to which peer is connected to.
void displayUser ()
displays the content of the users array.
void setAmountOfClients (int clients)
Sets the amount of clients that will connect to the swarm during the simulation.
void initialize ()
Sets up the tracker.
void handleMessage (cMessage *msg)
Handles incomming mesasges.
void finish ()
Called upon finalisiation of the simulation.
Private Member Functions
vector< userID >::iterator peerLookUp (const char *peer)
Returns a pointer to the information of peer.
void sentToClient (const char *peer, cMessage *msg)
Sends message msg to peer.
int getGate (const char *peer)
Returns the gate at which peer is connected to.
int setGate (const char *peer, int gateNum)
Registers the gate at which peer is connected to.
void getRandomPeers (TrackerResponse *tr, unsigned int numWanted, const char *peer)
Adds numWanted random peers to the tracker response message tr.
Private Attributes
short complete
Amount of seeders in the swarm.
short incomplete
Amount of leechers in the swarm.
unsigned int left
Amount of clients that will connect in the future to the swarm.
int amountOfClients
Total amount of clients that will connect in the simulation.
int peersinswarm
Amount of peers in the swarm.
cOutVector completedpeers
cOutVector totpeers
cOutVector totseeds
int interval
Defines the time in which each BT client should report himself back.
vector< userID > users
Array containing every registred BT client at the tracker.
Detailed Description
The BTTracker class implements the tracker functionalities.
Date:
2009-06-09
Version:
1.2
Author:
Blekinge Institute of Technology TEK-ATS
Constructor & Destructor Documentation
BTTracker::BTTracker ()
References amountOfClients, complete, incomplete, interval, left, and BitTorrent::peer_id.
Member Function Documentation
void BTTracker::displayUser ()
displays the content of the users array.
References users.
void BTTracker::finish ()
Called upon finalisiation of the simulation.
This is done by OMNeT++ itself.
void BTTracker::freeGate (const char * peer) [virtual]
Frees the gate to which peer is connected to.
Implements BitTorrent.
References getGate().
int BTTracker::getGate (const char * peer) [private]
Returns the gate at which peer is connected to.
References peerLookUp(), and users.
Referenced by freeGate(), and sentToClient().
void BTTracker::getRandomPeers (TrackerResponse * tr, unsigned int numWanted, const char * peer) [private]
Adds numWanted random peers to the tracker response message tr.
References users.
Referenced by handleMessage().
void BTTracker::handleMessage (cMessage * msg)
Handles incomming mesasges.
This function is called by OMNeT++.
References amountOfClients, complete, userID::downloaded, userID::gate, getRandomPeers(), incomplete, interval, left, userID::left, userID::peer_id, peerLookUp(), sentToClient(), totpeers, totseeds, Tracker_Request, Tracker_Response, userID::uploaded, and users.
void BTTracker::initialize ()
Sets up the tracker.
Must be called upon creation of the simulation. This is done by OMNeT++ itself.
References complete, completedpeers, TorrentFile::getValue(), incomplete, peersinswarm, BitTorrent::torrentFile, totpeers, totseeds, and BitTorrent::URL.
vector< userID >::iterator BTTracker::peerLookUp (const char * peer) [private]
Returns a pointer to the information of peer.
References users.
Referenced by getGate(), and handleMessage().
void BTTracker::sentToClient (const char * peer, cMessage * msg) [private]
Sends message msg to peer.
References getGate().
Referenced by handleMessage().
void BTTracker::setAmountOfClients (int clients)
Sets the amount of clients that will connect to the swarm during the simulation.
this function is called by the ClientAssigner module at the start up of the simualtion.
References amountOfClients.
Referenced by ClientAssigner::initialize().
int BTTracker::setGate (const char * peer, int gateNum) [private]
Registers the gate at which peer is connected to.
Member Data Documentation
int BTTracker::amountOfClients [private]
Total amount of clients that will connect in the simulation.
Referenced by BTTracker(), handleMessage(), and setAmountOfClients().
short BTTracker::complete [private]
Amount of seeders in the swarm.
Referenced by BTTracker(), handleMessage(), and initialize().
cOutVector BTTracker::completedpeers [private]
Referenced by initialize().
short BTTracker::incomplete [private]
Amount of leechers in the swarm.
Referenced by BTTracker(), handleMessage(), and initialize().
int BTTracker::interval [private]
Defines the time in which each BT client should report himself back.
Referenced by BTTracker(), and handleMessage().
unsigned int BTTracker::left [private]
Amount of clients that will connect in the future to the swarm.
Referenced by BTTracker(), and handleMessage().
int BTTracker::peersinswarm [private]
Amount of peers in the swarm.
Referenced by initialize().
cOutVector BTTracker::totpeers [private]
Referenced by handleMessage(), and initialize().
cOutVector BTTracker::totseeds [private]
Referenced by handleMessage(), and initialize().
vector<userID> BTTracker::users [private]
Array containing every registred BT client at the tracker.
Referenced by displayUser(), getGate(), getRandomPeers(), handleMessage(), and peerLookUp().
The documentation for this class was generated from the following files:
BTTracker.h
BTTracker.cc