PieceManager Class Reference
PieceManager Class Reference
The PieceManager class manages all the information concerning pieces and blocks for a BT client.
#include <PieceManager.h>
Public Member Functions
PieceManager ()
~PieceManager ()
void setSeeder ()
Notifies the PieceManager class that the owner of this class is a seeder.
void init (double lengthFile, double pieceLengthIn, int algorithmIn)
Initialises this class, must first be called for proper functioning.
void setBlockLength (int blockSize)
Sets the length of the blocks, must first be called for proper functioning.
int setBlock (unsigned int piece, unsigned int block)
Adds a block of a piece to the incomplete piece set.
void addPiece (unsigned int piece, const char *peer)
Adds a piece in the piece set of peer.
int getPiecePresent (unsigned int piece)
Checks whether piece piece is present.
int getPiecePresentOfPeer (unsigned int piece, const char *peer)
Checks whether peer has piece.
int getPieceArrayComplete ()
Checks if the myPieceSet is complete.
int getAmountOfPieces ()
Returns the amount of pieces that are present in myPieceSet.
int getAmountOfCompletePieces ()
Returns the amount of pieces that are present in myPieceArray.
int getAmountOfPiecesInProgress ()
Returns the amount of pieces in progress of downloading.
int getLengthOfPieceArray ()
Returns the length of the piece array (in bytes).
double getLengthOfFile ()
Returns the length of the file that is being downloaded (in bytes).
void initialisePieceArray (double distri)
Fills myPieceArray with and uniform distribution.
int getPieceArrayCompleteOfPeer (const char *peer)
Checks whether the peice array of peer is complete.
int getBlockPresentOfIncompletePeer (unsigned int piece, unsigned int block, const char *peer)
Checks wether block is present in the block array of an incomplete piece being downloaded from peer.
void getLastBlocks (vector< blockID > *blocks)
Returns all the blocks from incompletePieces that are not yet downloaded.
void getDownloadListOfPeers (vector< string > *peers)
Returns a list of peers that currently is being downloaded from.
blockID pieceRequest (const char *peer)
Returns the ID of a block that can be downloaded from a peer.
void getRarestPieceSet (unsigned char *rarestSet, int level)
Returns the rarest piece set.
void buildPieceIndex ()
Recalculates the rarestPieceIndex array.
void addPieceArrayOfPeer (BitField *msg)
Adds a new entry for peer to the piecesOfPeer array.
int getPieceArrayEmpty (const char *peer)
Returns if the piece array of peer is empty.
int getPieceArrayComplete (const char *peer)
Returns if the piece array of peer is complete.
void writePiecesToMessage (BitField *msg)
Copies the content of myPieceSet in the bitfield message.
void freePeer (const char *peer)
Deletes every track of peer.
void setInterestedInPeer (const char *peer, bool interest)
Sets if the owner is interested in peer.
int getInterestedInPeer (const char *peer)
Returns if the owner is interested in peer.
void setChokedByPeer (const char *peer, bool choked)
Sets if the owner is choked by peer.
int getChokedByPeer (const char *peer)
Returns if the owner is choked by peer.
int isThereSomethingToBeInterestedIn (const char *peer)
Returns if there is something to be interested in from peer.
unsigned int getRemainingDownload ()
Returns the amount of bytes that is still to be downloaded.
void displayPiece ()
Displays the piece set to cout.
void displayPiece (const char *peer)
Displays the piece set of peer to cout.
void displayBlock ()
Displays the incomplete piece set to cout.
void displayPeers ()
Displays the peers of which a piece list is avialable to cout.
void setPeerID (string naam)
Sets the name of the owner of this class.
void deleteIncompletePieces ()
Removes every enry in the incomplete piece set.
Public Attributes
int acces
Defines the amount of time that myPieceArray was accesed.
Private Member Functions
vector< incompletePiece >::iterator incPieceLookUp (unsigned int pieceLU)
Returns pointer to in incomplete piece.
vector< pieceOfPeer >::iterator pieceOfPeerLookUp (const char *peer)
Returns pointer to the piece information of peer.
void addPiece (unsigned int stuk)
Adds a piece to the local piece set.
int getPieceArrayComplete (unsigned char *piece)
Checks if the passed piece array is complete.
int getBlockArrayComplete (unsigned char *block)
Checks if the passed block array is complete.
void getCompressedPieceList (unsigned char *pieceList, vector< int > *compressedPieceList)
Pushes Back all piece numbers from pieceList in the vector.
unsigned int getNextEmptyBlock (vector< incompletePiece >::iterator it)
Returns the first empty block of an incomplete piece.
unsigned int isLastBlock (vector< incompletePiece >::iterator it)
Returns if all block are present in incomplete piece it.
unsigned int getRandomPiece (const char *peer)
Gets a random piece from the piece set of peer.
int getBlockPresent (unsigned char *it, unsigned int block)
Checks wether a block is present in block array.
void throwOutOfPieces (unsigned char *pieceList, unsigned char *rarestSet)
Throws all the pieces out of rarestSet that this client has , which are not in pieceList and which are in process of downloading.
void freeIncompletePiece (const char *peer)
Sets every incomplete piece of peer to open to other peers.
void randomFirstPolicy (const char *peer, blockID *blockId)
Implementing the random first policy.
void strictPriorityPolicy (const char *peer, blockID *blockId)
Implementing the strict priority policy.
void rarestFirstPolicy (const char *peer, blockID *blockId)
Implementing the rarest first policy.
void addIncompletePiece (const char *peer, unsigned int index)
Adds an incomplete piece to incompletePieces vector.
void algLinear (const char *peer, blockID *blockId)
Implements the simple linear piece selection policy.
Private Attributes
bool seeder
Defines if the client owning this class is a seeder or not.
int algorithm
Defines the piece selection algorithm used.
unsigned char * myPieces
Pointer to an array of bits representing the pieces that this client owns.
short * rarestPieceIndex
Pointer to an array which stores how many duplicates of a piece is present in the swarm.
string name
Defines the name of the client owning this class.
int pieceLength
Defines the length of a piece.
int blockLength
Defines the length of a block.
int lastBlockLength
Defines the length of the last block.
int lastPieceLength
Defines the length of the last piece.
double lengthOfFile
Defines the length of the file being downloaded.
int amountOfPieces
Defines the amount of pieces in which the file is divided.
int amountOfBlocks
Defines the amount of blocks in which a peice is divided.
int lengthOfPieceArray
Defines the length of the piece array.
int lengthOfBlockArray
Defines the length of the block array.
int last_piece
unsigned int completed_pieces
unsigned char * power
Pointer to an array storing piece selection information.
vector< incompletePiece > incompletePieces
Array containing information about incomplete pieces.
vector< pieceOfPeer > piecesOfPeers
Array containing piece information of peers.
std::map< string, bool > completedPeers
Map that maps seeder/leecher state upon peers.
Detailed Description
The PieceManager class manages all the information concerning pieces and blocks for a BT client.
Date:
2009-03-06
Version:
1.2
Author:
Blekinge Institute of Technology TEK-ATS
Constructor & Destructor Documentation
PieceManager::PieceManager ()
References acces, amountOfBlocks, amountOfPieces, completed_pieces, last_piece, lastBlockLength, lastPieceLength, lengthOfBlockArray, lengthOfFile, myPieces, pieceLength, power, and seeder.
PieceManager::~PieceManager ()
Member Function Documentation
void PieceManager::addIncompletePiece (const char * peer, unsigned int index) [private]
Adds an incomplete piece to incompletePieces vector.
addIncompletePiece - add incomplete piece to incompletePieces vector.
Parameters:
peer The peer from which this piece will be downloaded
index The piece that will be downloaded
Author:
TEK-ATS, BTH
Date:
2007-10-23
Parameters:
peer - peer to download piece from
index - piece number
Returns:
void
See also:
References amountOfBlocks, incompletePiece::block, incompletePieces, incompletePiece::peer_id, and incompletePiece::piece.
Referenced by algLinear().
void PieceManager::addPiece (unsigned int piece, const char * peer)
Adds a piece in the piece set of peer.
References pieceOfPeerLookUp(), power, and rarestPieceIndex.
void PieceManager::addPiece (unsigned int stuk) [private]
Adds a piece to the local piece set.
References acces, completed_pieces, myPieces, name, and power.
Referenced by BTClient::handleHavePiece(), initialisePieceArray(), and setBlock().
void PieceManager::addPieceArrayOfPeer (BitField * msg)
Adds a new entry for peer to the piecesOfPeer array.
References pieceOfPeer::choked, pieceOfPeer::interested, pieceOfPeer::peer_id, pieceOfPeer::piece, and piecesOfPeers.
Referenced by BTClient::handleBitfield().
void PieceManager::algLinear (const char * peer, blockID * blockId) [private]
Implements the simple linear piece selection policy.
algLinear
Implements the simple linear piece selection algorithm.
Author:
David Erman, TEK-ATS, BTH
Date:
2007-10-23
Parameters:
peer - peer to download piece from.
blockId - piece do download. fill in blockId->index : the piece number blockId->offset : the block number blockId->length : the length of the block
Returns:
void
See also:
References addIncompletePiece(), amountOfPieces, blockLength, blockID::index, last_piece, blockID::length, and blockID::offset.
Referenced by pieceRequest().
void PieceManager::buildPieceIndex ()
Recalculates the rarestPieceIndex array.
References amountOfPieces, piecesOfPeers, power, and rarestPieceIndex.
Referenced by freePeer(), and BTClient::handleBitfield().
void PieceManager::deleteIncompletePieces ()
Removes every enry in the incomplete piece set.
References incompletePieces.
Referenced by BTClient::handlePiece().
void PieceManager::displayBlock ()
Displays the incomplete piece set to cout.
References amountOfBlocks, amountOfPieces, incompletePieces, and lengthOfBlockArray.
void PieceManager::displayPeers ()
Displays the peers of which a piece list is avialable to cout.
References amountOfPieces, and piecesOfPeers.
Referenced by isThereSomethingToBeInterestedIn().
void PieceManager::displayPiece (const char * peer)
Displays the piece set of peer to cout.
References amountOfPieces, lengthOfPieceArray, pieceOfPeerLookUp(), and piecesOfPeers.
void PieceManager::displayPiece ()
Displays the piece set to cout.
References amountOfBlocks, amountOfPieces, lengthOfPieceArray, and myPieces.
void PieceManager::freeIncompletePiece (const char * peer) [private]
Sets every incomplete piece of peer to open to other peers.
References incompletePieces.
Referenced by freePeer(), and setChokedByPeer().
void PieceManager::freePeer (const char * peer)
Deletes every track of peer.
Incomplete pieces will be freed and all user information will be deleted from the database.
References buildPieceIndex(), freeIncompletePiece(), pieceOfPeerLookUp(), and piecesOfPeers.
Referenced by BTClient::handlePeerIsGone().
int PieceManager::getAmountOfCompletePieces ()
Returns the amount of pieces that are present in myPieceArray.
References completed_pieces.
Referenced by BTClient::handlePiece(), and randomFirstPolicy().
int PieceManager::getAmountOfPieces ()
Returns the amount of pieces that are present in myPieceSet.
References amountOfPieces.
Referenced by BTClient::handlePiece(), and BTClient::handlePieceRequest().
int PieceManager::getAmountOfPiecesInProgress ()
Returns the amount of pieces in progress of downloading.
References incompletePieces.
Referenced by BTClient::handlePiece().
int PieceManager::getBlockArrayComplete (unsigned char * block) [private]
Checks if the passed block array is complete.
References amountOfBlocks, and power.
Referenced by setBlock().
int PieceManager::getBlockPresent (unsigned char * it, unsigned int block) [private]
Checks wether a block is present in block array.
References power.
Referenced by getBlockPresentOfIncompletePeer(), getLastBlocks(), and setBlock().
int PieceManager::getBlockPresentOfIncompletePeer (unsigned int piece, unsigned int block, const char * peer)
Checks wether block is present in the block array of an incomplete piece being downloaded from peer.
Parameters:
piece The piece to be checked
block The block to be checked
peer The peer to be checked
Return values:
0 Block is present
-1 Block is not present
References getBlockPresent(), and incompletePieces.
Referenced by BTClient::handlePiece().
int PieceManager::getChokedByPeer (const char * peer)
Returns if the owner is choked by peer.
Return values:
0 choked
-1 unchoked
References pieceOfPeerLookUp(), and piecesOfPeers.
Referenced by BTClient::handlePiece().
void PieceManager::getCompressedPieceList (unsigned char * pieceList, vector< int > * compressedPieceList) [private]
Pushes Back all piece numbers from pieceList in the vector.
References amountOfPieces, and power.
Referenced by getRandomPiece(), and rarestFirstPolicy().
void PieceManager::getDownloadListOfPeers (vector< string > * peers)
Returns a list of peers that currently is being downloaded from.
Parameters:
peers Pointer to a vector on which all the ID of the peers will be pushed.
References piecesOfPeers.
Referenced by BTClient::handlePiece().
int PieceManager::getInterestedInPeer (const char * peer)
Returns if the owner is interested in peer.
Return values:
0 interested
-1 not interested
-2 peer not found
References pieceOfPeerLookUp(), and piecesOfPeers.
Referenced by BTClient::handleHavePiece(), and BTClient::handlePiece().
void PieceManager::getLastBlocks (vector< blockID > * blocks)
Returns all the blocks from incompletePieces that are not yet downloaded.
Parameters:
blocks A pointer to a vector on which all the IDs of the blocks will be pushed back.
References amountOfBlocks, blockLength, getBlockPresent(), incompletePieces, blockID::index, lastBlockLength, blockID::length, and blockID::offset.
Referenced by BTClient::handlePiece().
double PieceManager::getLengthOfFile () [inline]
Returns the length of the file that is being downloaded (in bytes).
References lengthOfFile.
int PieceManager::getLengthOfPieceArray ()
Returns the length of the piece array (in bytes).
References lengthOfPieceArray.
Referenced by BTClient::handleBitfield(), and BTClient::handleHandshake().
unsigned int PieceManager::getNextEmptyBlock (vector< incompletePiece >::iterator it) [private]
Returns the first empty block of an incomplete piece.
References amountOfBlocks, and power.
Referenced by pieceRequest(), and strictPriorityPolicy().
int PieceManager::getPieceArrayComplete (const char * peer)
Returns if the piece array of peer is complete.
Return values:
0 piece set complete
-1 piece set incomplete
References amountOfPieces, pieceOfPeerLookUp(), and power.
int PieceManager::getPieceArrayComplete ()
Checks if the myPieceSet is complete.
Return values:
0 complete
-1 incomplete
References amountOfPieces, and completed_pieces.
int PieceManager::getPieceArrayComplete (unsigned char * piece) [private]
Checks if the passed piece array is complete.
References amountOfPieces, and power.
Referenced by BTClient::handlePiece().
int PieceManager::getPieceArrayCompleteOfPeer (const char * peer)
Checks whether the peice array of peer is complete.
Parameters:
peer The peer to be checked
Return values:
0 If array of peer is complete
-1 If array of peer is not complete
References amountOfPieces, completedPeers, pieceOfPeerLookUp(), piecesOfPeers, and power.
Referenced by BTClient::handleBitfield(), and BTClient::handleHavePiece().
int PieceManager::getPieceArrayEmpty (const char * peer)
Returns if the piece array of peer is empty.
Return values:
0 piece set is empty
-1 piece set is not empty
References lengthOfPieceArray, and pieceOfPeerLookUp().
Referenced by BTClient::handleBitfield().
int PieceManager::getPiecePresent (unsigned int piece)
Checks whether piece piece is present.
Return values:
0 present
-1 not present
References myPieces, and power.
Referenced by getRemainingDownload(), BTClient::handlePieceRequest(), and initialisePieceArray().
int PieceManager::getPiecePresentOfPeer (unsigned int piece, const char * peer)
Checks whether peer has piece.
Return values:
0 present
-1 not present
References pieceOfPeerLookUp(), piecesOfPeers, and power.
Referenced by strictPriorityPolicy().
unsigned int PieceManager::getRandomPiece (const char * peer) [private]
Gets a random piece from the piece set of peer.
References getCompressedPieceList(), lengthOfPieceArray, pieceOfPeerLookUp(), piecesOfPeers, and throwOutOfPieces().
Referenced by randomFirstPolicy(), and rarestFirstPolicy().
void PieceManager::getRarestPieceSet (unsigned char * rarestSet, int level)
Returns the rarest piece set.
Parameters:
rarestSet Pointer to an array in which the rarest pieces will be stored.
level The order of the rarest pieces to be requested. For example level 0 are the rarest pieces, level 1 are the second rarest pieces and so on.
References amountOfPieces, power, and rarestPieceIndex.
Referenced by rarestFirstPolicy().
unsigned int PieceManager::getRemainingDownload ()
Returns the amount of bytes that is still to be downloaded.
References amountOfPieces, getPiecePresent(), lastPieceLength, and pieceLength.
Referenced by BTClient::handleKeepAliveTimer(), BTClient::handlePiece(), BTClient::handleSelfMessage(), and BTClient::initialize().
vector< incompletePiece >::iterator PieceManager::incPieceLookUp (unsigned int pieceLU) [inline, private]
Returns pointer to in incomplete piece.
Return values:
vector.end() If the piece was not found.
References incompletePieces.
Referenced by setBlock(), and strictPriorityPolicy().
void PieceManager::init (double lengthFile, double pieceLengthIn, int algorithmIn)
Initialises this class, must first be called for proper functioning.
References algorithm, amountOfPieces, lastPieceLength, lengthOfFile, lengthOfPieceArray, myPieces, pieceLength, and rarestPieceIndex.
Referenced by BTClient::initialize().
void PieceManager::initialisePieceArray (double distri)
Fills myPieceArray with and uniform distribution.
The left bound is zero.
Parameters:
distri Is the right bound of the uniform distribution.
References addPiece(), amountOfPieces, and getPiecePresent().
Referenced by BTClient::initialize().
unsigned int PieceManager::isLastBlock (vector< incompletePiece >::iterator it) [private]
Returns if all block are present in incomplete piece it.
References amountOfBlocks, and power.
Referenced by pieceRequest(), and strictPriorityPolicy().
int PieceManager::isThereSomethingToBeInterestedIn (const char * peer)
Returns if there is something to be interested in from peer.
Parameters:
0 There are pieces to be interested in.
-1 There are no pieces to be interested in.
References displayPeers(), lengthOfPieceArray, myPieces, pieceOfPeerLookUp(), and piecesOfPeers.
Referenced by BTClient::handleHavePiece(), and BTClient::handlePiece().
vector< pieceOfPeer >::iterator PieceManager::pieceOfPeerLookUp (const char * peer) [inline, private]
Returns pointer to the piece information of peer.
Return values:
vector.end() If no information of peer could be found.
References piecesOfPeers.
Referenced by addPiece(), displayPiece(), freePeer(), getChokedByPeer(), getInterestedInPeer(), getPieceArrayComplete(), getPieceArrayCompleteOfPeer(), getPieceArrayEmpty(), getPiecePresentOfPeer(), getRandomPiece(), isThereSomethingToBeInterestedIn(), rarestFirstPolicy(), setChokedByPeer(), and setInterestedInPeer().
blockID PieceManager::pieceRequest (const char * peer)
Returns the ID of a block that can be downloaded from a peer.
This function calls the proper piece selection algorithms set in the initialisation file.
References algLinear(), algorithm, blockLength, getNextEmptyBlock(), incompletePieces, blockID::index, isLastBlock(), lastBlockLength, blockID::length, blockID::offset, randomFirstPolicy(), rarestFirstPolicy(), and strictPriorityPolicy().
Referenced by BTClient::requestNewPiece().
void PieceManager::randomFirstPolicy (const char * peer, blockID * blockId) [private]
Implementing the random first policy.
Parameters:
blockId pointer to a blockID in wich the selected piece will be written
References amountOfBlocks, incompletePiece::block, blockLength, getAmountOfCompletePieces(), getRandomPiece(), incompletePieces, blockID::index, blockID::length, blockID::offset, incompletePiece::peer_id, and incompletePiece::piece.
Referenced by pieceRequest().
void PieceManager::rarestFirstPolicy (const char * peer, blockID * blockId) [private]
Implementing the rarest first policy.
Parameters:
blockId pointer to a blockID in wich the selected piece will be written
References amountOfBlocks, incompletePiece::block, blockLength, getCompressedPieceList(), getRandomPiece(), getRarestPieceSet(), incompletePieces, blockID::index, blockID::length, lengthOfPieceArray, blockID::offset, incompletePiece::peer_id, incompletePiece::piece, pieceOfPeerLookUp(), and throwOutOfPieces().
Referenced by pieceRequest().
int PieceManager::setBlock (unsigned int piece, unsigned int block)
Adds a block of a piece to the incomplete piece set.
Returns:
Wheter peer was found in the database
Return values:
0 Block was added.
-1 Block was not added.
References addPiece(), getBlockArrayComplete(), getBlockPresent(), incompletePieces, incPieceLookUp(), and power.
Referenced by BTClient::handlePiece().
void PieceManager::setBlockLength (int blockSize)
Sets the length of the blocks, must first be called for proper functioning.
References amountOfBlocks, blockLength, lastBlockLength, lengthOfBlockArray, name, and pieceLength.
Referenced by BTClient::initialize().
void PieceManager::setChokedByPeer (const char * peer, bool choked)
Sets if the owner is choked by peer.
Parameters:
peer The peer of which the choke value should be set
choked choked or unchoked by that peer.
References freeIncompletePiece(), pieceOfPeerLookUp(), and piecesOfPeers.
Referenced by BTClient::handleChoke(), and BTClient::handleUnChoke().
void PieceManager::setInterestedInPeer (const char * peer, bool interest)
Sets if the owner is interested in peer.
References pieceOfPeerLookUp(), and piecesOfPeers.
Referenced by BTClient::handleBitfield(), and BTClient::handleHavePiece().
void PieceManager::setPeerID (string naam)
Sets the name of the owner of this class.
References name.
Referenced by BTClient::initialize().
void PieceManager::setSeeder ()
Notifies the PieceManager class that the owner of this class is a seeder.
References seeder.
Referenced by BTClient::handlePiece(), and BTClient::initialize().
void PieceManager::strictPriorityPolicy (const char * peer, blockID * blockId) [private]
Implementing the strict priority policy.
Parameters:
blockId pointer to a blockID in wich the selected piece will be written
References blockLength, getNextEmptyBlock(), getPiecePresentOfPeer(), incompletePieces, incPieceLookUp(), blockID::index, isLastBlock(), lastBlockLength, blockID::length, and blockID::offset.
Referenced by pieceRequest().
void PieceManager::throwOutOfPieces (unsigned char * pieceList, unsigned char * rarestSet) [private]
Throws all the pieces out of rarestSet that this client has , which are not in pieceList and which are in process of downloading.
References incompletePieces, lengthOfPieceArray, myPieces, and power.
Referenced by getRandomPiece(), and rarestFirstPolicy().
void PieceManager::writePiecesToMessage (BitField * msg)
Copies the content of myPieceSet in the bitfield message.
References lengthOfPieceArray, and myPieces.
Referenced by BTClient::handleBitfield(), and BTClient::handleHandshake().
Member Data Documentation
int PieceManager::acces
Defines the amount of time that myPieceArray was accesed.
Referenced by addPiece(), and PieceManager().
int PieceManager::algorithm [private]
Defines the piece selection algorithm used.
Referenced by init(), and pieceRequest().
int PieceManager::amountOfBlocks [private]
Defines the amount of blocks in which a peice is divided.
Referenced by addIncompletePiece(), displayBlock(), displayPiece(), getBlockArrayComplete(), getLastBlocks(), getNextEmptyBlock(), isLastBlock(), PieceManager(), randomFirstPolicy(), rarestFirstPolicy(), and setBlockLength().
int PieceManager::amountOfPieces [private]
Defines the amount of pieces in which the file is divided.
Referenced by algLinear(), buildPieceIndex(), displayBlock(), displayPeers(), displayPiece(), getAmountOfPieces(), getCompressedPieceList(), getPieceArrayComplete(), getPieceArrayCompleteOfPeer(), getRarestPieceSet(), getRemainingDownload(), init(), initialisePieceArray(), and PieceManager().
int PieceManager::blockLength [private]
Defines the length of a block.
Referenced by algLinear(), getLastBlocks(), pieceRequest(), randomFirstPolicy(), rarestFirstPolicy(), setBlockLength(), and strictPriorityPolicy().
unsigned int PieceManager::completed_pieces [private]
Referenced by addPiece(), getAmountOfCompletePieces(), getPieceArrayComplete(), and PieceManager().
std::map<string, bool> PieceManager::completedPeers [private]
Map that maps seeder/leecher state upon peers.
Referenced by getPieceArrayCompleteOfPeer().
vector<incompletePiece> PieceManager::incompletePieces [private]
Array containing information about incomplete pieces.
Referenced by addIncompletePiece(), deleteIncompletePieces(), displayBlock(), freeIncompletePiece(), getAmountOfPiecesInProgress(), getBlockPresentOfIncompletePeer(), getLastBlocks(), incPieceLookUp(), pieceRequest(), randomFirstPolicy(), rarestFirstPolicy(), setBlock(), strictPriorityPolicy(), and throwOutOfPieces().
int PieceManager::last_piece [private]
Referenced by algLinear(), and PieceManager().
int PieceManager::lastBlockLength [private]
Defines the length of the last block.
Referenced by getLastBlocks(), PieceManager(), pieceRequest(), setBlockLength(), and strictPriorityPolicy().
int PieceManager::lastPieceLength [private]
Defines the length of the last piece.
Referenced by getRemainingDownload(), init(), and PieceManager().
int PieceManager::lengthOfBlockArray [private]
Defines the length of the block array.
Referenced by displayBlock(), PieceManager(), and setBlockLength().
double PieceManager::lengthOfFile [private]
Defines the length of the file being downloaded.
Referenced by getLengthOfFile(), init(), and PieceManager().
int PieceManager::lengthOfPieceArray [private]
Defines the length of the piece array.
Referenced by displayPiece(), getLengthOfPieceArray(), getPieceArrayEmpty(), getRandomPiece(), init(), isThereSomethingToBeInterestedIn(), rarestFirstPolicy(), throwOutOfPieces(), and writePiecesToMessage().
unsigned char* PieceManager::myPieces [private]
Pointer to an array of bits representing the pieces that this client owns.
Every bit represents one piece.
Referenced by addPiece(), displayPiece(), getPiecePresent(), init(), isThereSomethingToBeInterestedIn(), PieceManager(), throwOutOfPieces(), and writePiecesToMessage().
string PieceManager::name [private]
Defines the name of the client owning this class.
This is only used in case debug messages want to be printed.
Referenced by addPiece(), setBlockLength(), and setPeerID().
int PieceManager::pieceLength [private]
Defines the length of a piece.
Referenced by getRemainingDownload(), init(), PieceManager(), and setBlockLength().
vector<pieceOfPeer> PieceManager::piecesOfPeers [private]
Array containing piece information of peers.
Referenced by addPieceArrayOfPeer(), buildPieceIndex(), displayPeers(), displayPiece(), freePeer(), getChokedByPeer(), getDownloadListOfPeers(), getInterestedInPeer(), getPieceArrayCompleteOfPeer(), getPiecePresentOfPeer(), getRandomPiece(), isThereSomethingToBeInterestedIn(), pieceOfPeerLookUp(), setChokedByPeer(), and setInterestedInPeer().
unsigned char* PieceManager::power [private]
Pointer to an array storing piece selection information.
Referenced by addPiece(), buildPieceIndex(), getBlockArrayComplete(), getBlockPresent(), getCompressedPieceList(), getNextEmptyBlock(), getPieceArrayComplete(), getPieceArrayCompleteOfPeer(), getPiecePresent(), getPiecePresentOfPeer(), getRarestPieceSet(), isLastBlock(), PieceManager(), setBlock(), and throwOutOfPieces().
short* PieceManager::rarestPieceIndex [private]
Pointer to an array which stores how many duplicates of a piece is present in the swarm.
The piecenumber must be used to index this array.
Referenced by addPiece(), buildPieceIndex(), getRarestPieceSet(), and init().
bool PieceManager::seeder [private]
Defines if the client owning this class is a seeder or not.
Referenced by PieceManager(), and setSeeder().
The documentation for this class was generated from the following files:
PieceManager.h
PieceManager.cc