TorrentFile Class Reference
TorrentFile Class Reference
#include <TorrentFile.h>
Public Member Functions
TorrentFile ()
void initialize ()
string getValue (const char *key)
void getInt (ifstream &inFile, ostringstream &entry)
void getString (ifstream &inFile, ostringstream &entry)
Protected Member Functions
int getNext (ifstream &inFile, ostringstream &entry)
Protected Attributes
map< string, string > torrent
string fileName
string announce
int lengthOfFile
double lengthOfFile_double
int piece_length
int lengthOfPieces
int amountOfPieces
int amountOfBlocks
Constructor & Destructor Documentation
TorrentFile::TorrentFile ()
References amountOfBlocks, amountOfPieces, announce, fileName, lengthOfFile, lengthOfFile_double, piece_length, and torrent.
Member Function Documentation
void TorrentFile::getInt (ifstream & inFile, ostringstream & entry)
Referenced by getNext().
int TorrentFile::getNext (ifstream & inFile, ostringstream & entry) [protected]
References getInt(), and getString().
void TorrentFile::getString (ifstream & inFile, ostringstream & entry)
Referenced by getNext().
string TorrentFile::getValue (const char * key)
References torrent.
Referenced by BTTracker::initialize(), and BTClient::initialize().
void TorrentFile::initialize ()
Member Data Documentation
int TorrentFile::amountOfBlocks [protected]
Referenced by TorrentFile().
int TorrentFile::amountOfPieces [protected]
Referenced by TorrentFile().
string TorrentFile::announce [protected]
Referenced by TorrentFile().
string TorrentFile::fileName [protected]
Referenced by TorrentFile().
int TorrentFile::lengthOfFile [protected]
Referenced by TorrentFile().
double TorrentFile::lengthOfFile_double [protected]
Referenced by TorrentFile().
int TorrentFile::lengthOfPieces [protected]
int TorrentFile::piece_length [protected]
Referenced by TorrentFile().
map<string,string> TorrentFile::torrent [protected]
Referenced by getValue(), and TorrentFile().
The documentation for this class was generated from the following files:
TorrentFile.h
TorrentFile.cc